name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  GITHUB_WORKFLOW: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    # test matrix
    strategy:
      fail-fast: false
      matrix:
        python:
          - 3.8
          - 3.9
          - "3.10"
          - 3.11
          - 3.12
        django:
          - 4.2
          - 5.0
          - 5.1
        exclude:
          # django 5.0
          - python: 3.8
            django: 5.0
          - python: 3.9
            django: 5.0
          # django 5.1
          - python: 3.8
            django: 5.1
          - python: 3.9
            django: 5.1

    steps:
      # check out revision to test
      - uses: actions/checkout@v4

      # install python
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      # upgrade pip
      - name: Update pip
        run: python -m pip install --upgrade pip

      - name: Install Django 4.2
        if: matrix.django == 4.2
        run: pip install "Django>=4.2,<5.0"
      - name: Install Django 5.0
        if: matrix.django == 5.0
        run: pip install "Django>=5.0,<5.1"
      - name: Install Django 5.1
        if: matrix.django == 5.1
        run: pip install "Django>=5.1,<5.2"

      - name: Install dependencies
        run: pip install -U coverage freezegun time-machine setuptools

      - name: Install package
        run: pip install -e .

      # execute the tests
      - name: Run tests
        run: coverage run --source=django_slowtests manage.py test

      - name: Store coverage file
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: .coverage
